redis:
  image: redis:5.0.6

postgres:
  image: postgres:12.0
  environment:
    - POSTGRES_USER:postgres
    - POSTGRES_PASSWORD:postgres
  volumes:
    - ./data:/var/lib/postgresql/data

sentry:
  image: sentry:9.1.2
  links:
   - redis
   - postgres
  ports:
   - 8088:9000
  env_file:
    - sentry-variables.env

sentry-cron:
  image: sentry:9.1.2
  links:
   - redis
   - postgres
  command: "sentry run cron"
  env_file:
    - sentry-variables.env

sentry-worker-1:
  image: sentry:9.1.2
  links:
   - redis
   - postgres
  command: "sentry run worker"
  env_file:
    - sentry-variables.env
